---

coreos_baremetal_version: "v0.3.0"
coreos_baremetal_coreos_channel: "alpha"
coreos_baremetal_coreos_version: "1053.2.0"

coreos_baremetal_tmp_file: "/tmp/ignition.json"
coreos_baremetal_install_device: "/dev/sda"
coreos_baremetal_install_device_format: "ext4"

coreos_baremetal_binary_parent_dir: "/opt"
coreos_baremetal_symlink_bin_dir: "/usr/local/bin"
coreos_baremetal_service_dir: "/etc/init"

coreos_baremetal_git_dir: "/opt/coreos-baremetal"
coreos_baremetal_git_data_dir: "/opt/coreos-baremetal/examples"
coreos_baremetal_git_assets_dir: "/opt/coreos-baremetal/examples/assets"
coreos_baremetal_git_cloud_dir: "/opt/coreos-baremetal/examples/cloud"
coreos_baremetal_git_groups_dir: "/opt/coreos-baremetal/examples/groups/etcd-docker"
coreos_baremetal_git_ignition_dir: "/opt/coreos-baremetal/examples/ignition"
coreos_baremetal_git_profiles_dir: "/opt/coreos-baremetal/examples/profiles"

coreos_baremetal_bootcfg_address: "0.0.0.0:8080"
coreos_baremetal_bootcfg_data_dir: "/var/lib/bootcfg"
coreos_baremetal_bootcfg_assets_dir: "/var/lib/bootcfg/assets"
coreos_baremetal_bootcfg_cloud_dir: "/var/lib/bootcfg/cloud"
coreos_baremetal_bootcfg_groups_dir: "/var/lib/bootcfg/groups"
coreos_baremetal_bootcfg_ignition_dir: "/var/lib/bootcfg/ignition"
coreos_baremetal_bootcfg_profiles_dir: "/var/lib/bootcfg/profiles"

# CERTIFICATE GENERATION AND SERVING
#
# The following are k8s cert gen vars, in the coreos github repo
# There's a scripts/k8s_gen_certs.sh file which  creates the ca key and cert for the cluster

coreos_baremetal_k8s_server_ip: "127.0.0.1"
#coreos_baremetal_k8s_server_ip: "192.168.0.151"

coreos_baremetal_k8s_san_master_ips: []
#coreos_baremetal_k8s_san_master_ips:
#  - "IP.1=10.30.0.1"
#  - "IP.2=192.168.0.151"

coreos_baremetal_k8s_san_worker_ips: []
#coreos_baremetal_k8s_san_worker_ips:
#  - "IP.1=192.168.0.152"
#  - "IP.2=192.168.0.153"

# PXE CLOUD_CONFIG IGNITION TEMPLATE RELATED CONFIGS BELOW
#
# The ipxe boot environment which the bootcfg API makes requests like /grub /boot.ipxe /ipxe and /ignition available
# with params like uuid=<uuid>&mac=<address>&os=installed, defined in the selector hash.
# There are 3 main objects. groups, profiles, ignition
# The API by default listens on 8080, as well as data and assets dir is /var/lib/bootcfg and /var/lib/bootcfg/assets
#
# Since templates are most useful for ignitions/cloud-configs

# TEMPLATES
# Templates are placed in the role's templates dir, in ignition/
# These templates havent been altered much from the originals.
# Except the dashboard and ingress have been added to the k8s-master.yaml

coreos_baremetal_ignition_templates: []
#coreos_baremetal_ignition_templates:
#  - src: "ignition/default.yaml"
#    dest: "{{ coreos_baremetal_bootcfg_ignition_dir }}/default.yaml"
#  - src: "ignition/k8s-master.yaml"
#    dest: "{{ coreos_baremetal_bootcfg_ignition_dir }}/k8s-master.yaml"
#  - src: "ignition/k8s-worker.yaml"
#    dest: "{{ coreos_baremetal_bootcfg_ignition_dir }}/k8s-worker.yaml"

coreos_baremetal_ignition_groups: []
#coreos_baremetal_ignition_groups:
#  - id: "default"
#    name: "default"
#    profile: "default"
#    metadata:
#      coreos_channel: "alpha"
#      coreos_version: "1053.2.0"
#      ignition_endpoint: "http://192.168.0.10:8080/ignition"
#      baseurl: "http://192.168.0.10:8080/assets/coreos"
#      ssh_authorized_keys:
#        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/PMJ7B/EiWn51N0jIGpUcVxg+GuWCMnudK+/sySNguhtQYXHOMGXVP3I7RkyjMD+y18K27YABAgrQMtexowlZKFI/dTdPAZCob7m2pr4RyW6UySp6bPNzldHhN0iyHqt2/gnfXLX2OCwGe8yGsCsWEIb19xaYWJkL/0rmKaq82/vqqMOmBko3JOom1UPExr9TXc8kQCBXVVL1U9WQyOJnZewPlrbzj8xIdtUX5Vv5lmU2VsLl+vvC7fNnLJeCocWjdfGf1j0eTJtAYgSc2FujrjNhfU0+YTRs9hextq4SQlgHPHA4KNIfZdxT9/mOIET1I5L0+dNf0VawZJD0Gpf/
#  - id: "pxe"
#    name: "Master Node"
#    profile: "k8s-master-install"
#    selector: 
#      os: "installed"
#      mac: "08:00:27:2B:EB:89"
#    metadata: 
#      etcd_initial_cluster: "pxe=http://192.168.0.151:2380,pxe2=http://192.168.0.152:2380,pxe3=http://192.168.0.153:2380"
#      etcd_name: "pxe"
#      fleet_metadata: "role=etcd,name=pxe"
#      ipv4_address: "192.168.0.151"
#      k8s_cert_endpoint: "http://192.168.0.10:8080/assets"
#      k8s_dns_service_ip: "10.30.0.10"
#      k8s_etcd_endpoints: "http://192.168.0.151:2379,http://192.168.0.152:2379,http://192.168.0.153:2379"
#      k8s_pod_network: "10.20.0.0/16"
#      k8s_service_ip_range: "10.30.0.0/24"
#      skip_networkd: "true"
#      networkd_address: "192.168.0.151/24"
#      networkd_dns: "192.168.0.10"
#      networkd_gateway: "192.168.0.1"
#      ssh_authorized_keys: 
#        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/PMJ7B/EiWn51N0jIGpUcVxg+GuWCMnudK+/sySNguhtQYXHOMGXVP3I7RkyjMD+y18K27YABAgrQMtexowlZKFI/dTdPAZCob7m2pr4RyW6UySp6bPNzldHhN0iyHqt2/gnfXLX2OCwGe8yGsCsWEIb19xaYWJkL/0rmKaq82/vqqMOmBko3JOom1UPExr9TXc8kQCBXVVL1U9WQyOJnZewPlrbzj8xIdtUX5Vv5lmU2VsLl+vvC7fNnLJeCocWjdfGf1j0eTJtAYgSc2FujrjNhfU0+YTRs9hextq4SQlgHPHA4KNIfZdxT9/mOIET1I5L0+dNf0VawZJD0Gpf/
#  - id: "pxe2"
#    name: "Worker Node"
#    profile: "k8s-worker-install"
#    selector: 
#      os: "installed"
#      mac: "08:00:27:23:37:EF"
#    metadata: 
#      etcd_initial_cluster: "pxe=http://192.168.0.151:2380,pxe2=http://192.168.0.152:2380,pxe3=http://192.168.0.153:2380"
#      etcd_name: "pxe2"
#      fleet_metadata: "role=etcd,name=pxe2"
#      ipv4_address: "192.168.0.152"
#      k8s_cert_endpoint: "http://192.168.0.10:8080/assets"
#      k8s_controller_endpoint: "https://192.168.0.151"
#      k8s_dns_service_ip: "10.3.0.10"
#      k8s_etcd_endpoints: "http://192.168.0.151:2379,http://192.168.0.152:2379,http://192.168.0.153:2379"
#      skip_networkd: "true"
#      networkd_address: "192.168.0.152/24"
#      networkd_dns: "192.168.0.10"
#      networkd_gateway: "192.168.0.1"
#      ssh_authorized_keys: 
#        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/PMJ7B/EiWn51N0jIGpUcVxg+GuWCMnudK+/sySNguhtQYXHOMGXVP3I7RkyjMD+y18K27YABAgrQMtexowlZKFI/dTdPAZCob7m2pr4RyW6UySp6bPNzldHhN0iyHqt2/gnfXLX2OCwGe8yGsCsWEIb19xaYWJkL/0rmKaq82/vqqMOmBko3JOom1UPExr9TXc8kQCBXVVL1U9WQyOJnZewPlrbzj8xIdtUX5Vv5lmU2VsLl+vvC7fNnLJeCocWjdfGf1j0eTJtAYgSc2FujrjNhfU0+YTRs9hextq4SQlgHPHA4KNIfZdxT9/mOIET1I5L0+dNf0VawZJD0Gpf/
#  - id: "pxe3"
#    name: "Worker Node"
#    profile: "k8s-worker-install"
#    selector: 
#      os: "installed"
#      mac: "08:00:27:DB:CE:DC"
#    metadata: 
#      etcd_initial_cluster: "pxe=http://192.168.0.151:2380,pxe2=http://192.168.0.152:2380,pxe3=http://192.168.0.153:2380"
#      etcd_name: "pxe3"
#      fleet_metadata: "role=etcd,name=pxe3"
#      ipv4_address: "192.168.0.153"
#      k8s_cert_endpoint: "http://192.168.0.10:8080/assets"
#      k8s_controller_endpoint: "https://192.168.0.151"
#      k8s_dns_service_ip: "10.3.0.10"
#      k8s_etcd_endpoints: "http://192.168.0.151:2379,http://192.168.0.152:2379,http://192.168.0.153:2379"
#      skip_networkd: "true"
#      networkd_address: "192.168.0.153/24"
#      networkd_dns: "192.168.0.10"
#      networkd_gateway: "192.168.0.1"
#      ssh_authorized_keys: 
#        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/PMJ7B/EiWn51N0jIGpUcVxg+GuWCMnudK+/sySNguhtQYXHOMGXVP3I7RkyjMD+y18K27YABAgrQMtexowlZKFI/dTdPAZCob7m2pr4RyW6UySp6bPNzldHhN0iyHqt2/gnfXLX2OCwGe8yGsCsWEIb19xaYWJkL/0rmKaq82/vqqMOmBko3JOom1UPExr9TXc8kQCBXVVL1U9WQyOJnZewPlrbzj8xIdtUX5Vv5lmU2VsLl+vvC7fNnLJeCocWjdfGf1j0eTJtAYgSc2FujrjNhfU0+YTRs9hextq4SQlgHPHA4KNIfZdxT9/mOIET1I5L0+dNf0VawZJD0Gpf/

coreos_baremetal_ignition_profiles: []
#coreos_baremetal_ignition_profiles:
#  - id: "default"
#    name: "default"
#    boot: 
#      kernel: "/assets/coreos/1053.2.0/coreos_production_pxe.vmlinuz"
#      initrd: 
#        - "/assets/coreos/1053.2.0/coreos_production_pxe_image.cpio.gz"
#      cmdline: 
#        coreos.config.url: "http://192.168.0.10:8080/ignition?uuid=${uuid}&mac=${net0/mac:hexhyp}"
#        coreos.autologin: ""
#        coreos.first_boot: ""
#    cloud_id: ""
#    ignition_id: "default.yaml"
#  - id: "k8s-master-install"
#    name: "Kubernetes Master Install"
#    boot: 
#      kernel: "/assets/coreos/1053.2.0/coreos_production_pxe.vmlinuz"
#      initrd: 
#        - "/assets/coreos/1053.2.0/coreos_production_pxe_image.cpio.gz"
#      cmdline: 
#        coreos.config.url: "http://192.168.0.10:8080/ignition?uuid=${uuid}&mac=${net0/mac:hexhyp}"
#        coreos.autologin: ""
#        coreos.first_boot: ""
#    cloud_id: ""
#    ignition_id: "k8s-master.yaml"
#  - id: "k8s-worker-install"
#    name: "Kubernetes Worker Install"
#    boot: 
#      kernel: "/assets/coreos/1053.2.0/coreos_production_pxe.vmlinuz"
#      initrd: 
#        - "/assets/coreos/1053.2.0/coreos_production_pxe_image.cpio.gz"
#      cmdline: 
#        coreos.config.url: "http://192.168.0.10:8080/ignition?uuid=${uuid}&mac=${net0/mac:hexhyp}"
#        coreos.autologin: ""
#        coreos.first_boot: ""
#    cloud_id: ""
#    ignition_id: "k8s-worker.yaml"