---

- name: Create {{ kubectl_k8s_secrets_dir }} dir
  file:
    dest: "{{ kubectl_k8s_secrets_dir }}"
    state: directory

- name: Template App Secret to {{ kubectl_k8s_secrets_dir }} dir
  template:
    src: "secrets/appweb_secret.yaml.j2"
    dest: "{{ kubectl_k8s_secrets_dir }}/appweb_secret.yaml"

- name: Template Docker Registry Secret to {{ kubectl_k8s_secrets_dir }} dir
  template:
    src: "secrets/docker_registry_secret.yaml.j2"
    dest: "{{ kubectl_k8s_secrets_dir }}/docker_registry_secret.yaml"