---

- name: Install isc-dhcp-server from apt
  apt:
    name: isc-dhcp-server
    update_cache: yes
    cache_valid_time: 3600

- name: Template /etc/dhcp/dhcpd.conf
  template:
    src: etc/dhcp/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    backup: yes

- name: Restart isc-dhcp-server
  service:
    name: "isc-dhcp-server"
    state: restarted