---

- name: Ensure git present
  apt:
    name: git
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure bootcfg and git dirs present
  register: bootcfg_data_dir
  file:
    dest: "{{ item.dest }}"
    state: directory
    mode: "{{ item.mode | default('0777') }}"
  with_items:
    - dest: "{{ coreos_baremetal_git_dir }}"
    - dest: "{{ coreos_baremetal_bootcfg_data_dir }}"
    - dest: "{{ coreos_baremetal_bootcfg_assets_dir }}"
    - dest: "{{ coreos_baremetal_bootcfg_cloud_dir }}"
    - dest: "{{ coreos_baremetal_bootcfg_groups_dir }}"
    - dest: "{{ coreos_baremetal_bootcfg_ignition_dir }}"
    - dest: "{{ coreos_baremetal_bootcfg_profiles_dir }}"
  ignore_errors: yes

- name: Extract CoreOS Baremetal bootcfg binary
  unarchive:
    src: "https://github.com/coreos/coreos-baremetal/releases/download/{{ coreos_baremetal_version }}/bootcfg-{{ coreos_baremetal_version }}-linux-amd64.tar.gz"
    dest: "/opt"
    copy: no
    creates: "/opt/bootcfg-{{ coreos_baremetal_version }}/bootcfg"

- name: Symlink CoreOS Baremetal bootcfg binary to /usr/local/bin
  file:
    src: "{{ coreos_baremetal_binary_parent_dir }}/bootcfg-{{ coreos_baremetal_version }}/bootcfg"
    dest: "{{ coreos_baremetal_symlink_bin_dir }}/bootcfg"
    state: link

- name: Download Git repo
  git:
    repo: "https://github.com/coreos/coreos-baremetal.git"
    dest: "{{ coreos_baremetal_git_dir }}"
    update: no

- name: Run get-coreos script 
  shell: "./scripts/get-coreos {{ coreos_baremetal_coreos_channel }} {{ coreos_baremetal_coreos_version }}"
  args:
    chdir: "{{ coreos_baremetal_git_dir }}"
    creates: "{{ coreos_baremetal_git_assets_dir }}/coreos/{{ coreos_baremetal_coreos_version }}/coreos_production_pxe.vmlinuz"

- name: Rsync {{ coreos_baremetal_git_assets_dir }}/coreos/ to {{ coreos_baremetal_bootcfg_data_dir }}/assets
  synchronize:
    src: "{{ coreos_baremetal_git_assets_dir }}"
    dest: "{{ coreos_baremetal_bootcfg_data_dir }}"
  delegate_to: "{{ inventory_hostname }}"

#- name: Copy git to bootcfg dir
#  synchronize:
#    src: "{{ coreos_baremetal_git_data_dir }}"
#    dest: "{{ coreos_baremetal_bootcfg_data_dir }}"
#  delegate_to: "{{ inventory_hostname }}"

- name: Template Upstart bootcfg service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0775"
    owner: "root"
  with_items:
    - src: "bootcfg.conf"
      dest: "{{ coreos_baremetal_service_dir }}/bootcfg.conf"

- name: Template groups profiles ignition configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "groups/default.json"
      dest: "{{ coreos_baremetal_bootcfg_groups_dir }}/default.json"
    - src: "groups/pxe.json"
      dest: "{{ coreos_baremetal_bootcfg_groups_dir }}/pxe.json"
    - src: "groups/pxe2.json"
      dest: "{{ coreos_baremetal_bootcfg_groups_dir }}/pxe2.json"
    - src: "groups/pxe3.json"
      dest: "{{ coreos_baremetal_bootcfg_groups_dir }}/pxe3.json"
    - src: "profiles/default.json"
      dest: "{{ coreos_baremetal_bootcfg_profiles_dir }}/default.json"
    - src: "profiles/k8s-master-install.json"
      dest: "{{ coreos_baremetal_bootcfg_profiles_dir }}/k8s-master-install.json"
    - src: "profiles/k8s-worker-install.json"
      dest: "{{ coreos_baremetal_bootcfg_profiles_dir }}/k8s-worker-install.json"
    - src: "ignition/default.yaml"
      dest: "{{ coreos_baremetal_bootcfg_ignition_dir }}/default.yaml"
    - src: "ignition/k8s-master.yaml"
      dest: "{{ coreos_baremetal_bootcfg_ignition_dir }}/k8s-master.yaml"
    - src: "ignition/k8s-worker.yaml"
      dest: "{{ coreos_baremetal_bootcfg_ignition_dir }}/k8s-worker.yaml"

- name: Generate Certs and kubeconfig to {{ coreos_baremetal_bootcfg_assets_dir }}/tls/kubeconfig
  shell: "./scripts/tls/k8s-certgen -d {{ coreos_baremetal_bootcfg_assets_dir }}/tls -s 192.168.0.151 -m IP.1=10.30.0.1,IP.2=192.168.0.151 -w IP.1=192.168.0.152,IP.2=192.168.0.153"
  args:
    chdir: "{{ coreos_baremetal_git_dir }}"
    creates: "{{ coreos_baremetal_bootcfg_assets_dir }}/tls/kubeconfig"

- name: Ensure bootcfg service started
  service:
    name: bootcfg
    pattern: "{{ coreos_baremetal_service_dir }}/bootcfg.conf"
    state: started

#bootcfg -address 0.0.0.0:8080 -data-path /opt/coreos-baremetal/examples -assets-path /opt/coreos-baremetal/examples/assets
#sudo docker run -p 8080:8080 --rm -v $PWD/examples:/var/lib/bootcfg:Z -v $PWD/examples/groups/etcd-docker:/var/lib/bootcfg/groups:Z quay.io/coreos/bootcfg:latest -address=0.0.0.0:8080 -log-level=debug
