#cloud-config
---
coreos:
  update:
    reboot-strategy: 'off'
  etcd2:
    name: e1
    initial-cluster: e1=http://172.17.4.51:2380,e2=http://172.17.4.52:2380,e3=http://172.17.4.53:2380
    advertise-client-urls: http://$private_ipv4:2379
    listen-client-urls: http://0.0.0.0:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-peer-urls: http://$private_ipv4:2380
  units:
  - name: etcd2.service
    command: start