---

core_servers:
  hosts: [ core1.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
docker_servers:
  children: [ core_servers ]
docker_registry_servers:
  children: [ core_servers ]
all:
  children: [ core_servers, docker_servers, docker_registry_servers ]
_meta:
  hostvars:
    core1.lan:
      vagrant_ip: "192.168.0.10"