---

- name: Ensure docker engine and registry present on docker_registry_servers
  hosts: docker_registry_servers
  gather_facts: yes
  become: yes
  become_user: root
  vars_files:
    - vars/makevault.yml
  roles:
    - role: openssl
      openssl_generator_complexity: 4096
    - role: docker_registry
      docker_registry_users: "{{ authorized_registry_users }}"